name: Java CI with Maven


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
        BASE_URL: https://dev.onion.gnapitech.org
        BROWSER: ${{ secrets.BROWSER }}
        
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven (headless)
        working-directory: ${{ github.workspace }}
        run: mvn verify -Dheadless=true -DBASE_URL="${{ env.BASE_URL }}" -DBROWSER="${{ env.BROWSER }}"
